version: "3.8"

services:
  ranker:
    image: mpoc/ranker
    restart: always
    environment:
      MONGO_CONNECTION_STRING: mongodb://db:27017/ranker
    ports:
      - 8001:8000
    depends_on:
      - db
  db:
    image: mongo:4.4
    restart: always
    volumes:
      - ranker-db:/data/db

volumes:
  ranker-db:
